// =============================================================================
//  Hero.tsx — Hero section
//  ⚠️  Do not edit this file. Customise via hero.config.ts and site.config.ts.
// =============================================================================

import { motion } from "framer-motion";
import NetworkBackground from "./NetworkBackground";
import heroConfig from "../ConfigFiles/heroConfig";
import siteConfig from "../ConfigFiles/siteConfig";

const Hero = () => {
  const handleCtaClick = () => {
    document
      .querySelector(siteConfig.primaryCtaHref)
      ?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return (
    <section
      className="relative min-h-[100svh] w-full overflow-hidden bg-black"
      id="home"
    >
      {/* Background Image — locked as part of template theme */}
      <img
        src="/hero-bg-img.png"
        alt=""
        aria-hidden="true"
        className="absolute inset-0 h-full w-full object-cover object-top"
      />

      {/* Network Animation Layer — locked as part of template theme */}
      <NetworkBackground />

      {/* Diagonal Animated Grid — locked */}
      <motion.div
        className="absolute inset-0
          bg-[linear-gradient(rgba(255,255,255,0.05)_1px,transparent_1px),
              linear-gradient(90deg,rgba(255,255,255,0.05)_1px,transparent_1px)]
          bg-[size:70px_70px]"
        initial={{ opacity: 0 }}
        animate={{
          opacity: 0.35,
          backgroundPosition: ["0px 0px", "140px 140px"],
        }}
        transition={{
          opacity: { duration: 1.2 },
          backgroundPosition: {
            duration: 40,
            repeat: Infinity,
            ease: "linear",
          },
        }}
      />

      {/* Soft Glow Sweep — locked */}
      <motion.div
        className="absolute inset-0 pointer-events-none"
        animate={{ opacity: [0.25, 0.4, 0.25] }}
        transition={{ duration: 10, repeat: Infinity, ease: "easeInOut" }}
      >
        <div
          className="absolute left-1/3 top-[-30%] h-[160%] w-[35%]
          bg-gradient-to-b from-blue-500/10 via-cyan-500/10 to-transparent
          blur-[120px]"
        />
      </motion.div>

      {/* Vignette — locked */}
      <div className="absolute inset-0 bg-gradient-to-b from-black/40 via-black/20 to-black/75" />

      {/* Content */}
      <div className="relative z-10 flex min-h-[100svh] items-center justify-center px-6 pt-20">
        <div className="max-w-4xl text-center">

          {/* Headline */}
          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.9, ease: "easeOut" }}
            className="text-4xl sm:text-5xl md:text-6xl font-semibold tracking-tight text-white"
          >
            {heroConfig.headlinePrimary}
            <br />
            <span className="text-white/90">{heroConfig.headlineAccent}</span>
          </motion.h1>

          {/* Subtext */}
          <motion.p
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.9, delay: 0.2 }}
            className="mt-6 text-base sm:text-lg text-white/70 leading-relaxed"
          >
            {heroConfig.subtext}
          </motion.p>

          {/* CTA Button */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.9, delay: 0.4 }}
            className="mt-10 flex justify-center"
          >
            <button
              onClick={handleCtaClick}
              aria-label={`${heroConfig.ctaText} — scroll to ${siteConfig.primaryCtaHref}`}
              className="rounded-full px-16 py-4 text-sm font-medium text-white
                bg-gradient-to-r from-blue-500 to-cyan-400
                shadow-lg shadow-cyan-500/20 hover:opacity-90 transition"
            >
              {heroConfig.ctaText}
            </button>
          </motion.div>

        </div>
      </div>
    </section>
  );
};

export default Hero;