// =============================================================================
//  NavbarShared.tsx — Internal sub-components
//  ⚠️  Do not edit this file. Customise via navbar.config.ts instead.
// =============================================================================

import React from 'react';
import { motion } from 'framer-motion';
import type { NavLink, NavbarConfig } from '../ConfigFiles/navbarConfig';
import siteConfig from '../ConfigFiles/siteConfig';

// ─── LOGO ─────────────────────────────────────────────────────────────────────

interface LogoProps {
  // navbarConfig is no longer needed here — logo data lives in siteConfig
  onClick: () => void;
}

export const Logo: React.FC<LogoProps> = ({ onClick }) => (
  <motion.a
    href={siteConfig.navLinks[0]?.href ?? '#'}
    aria-label="Go to homepage"
    onClick={(e) => { e.preventDefault(); onClick(); }}
    className="flex items-center"
    whileHover={{ scale: 1.02 }}
    transition={{ duration: 0.2 }}
  >
    {siteConfig.logo.src ? (
      <img
        src={siteConfig.logo.src}
        alt={siteConfig.logo.alt}
        width={120}
        height={40}
        style={{ display: 'block' }}
      />
    ) : (
      <span className="text-white font-semibold text-lg tracking-tight">
        {siteConfig.logo.text}
      </span>
    )}
  </motion.a>
);

// ─── DESKTOP NAV LINKS ────────────────────────────────────────────────────────

interface DesktopLinksProps {
  links: NavLink[];
  activeLink: string;
  hoveredLink: string | null;
  layoutId: string; // unique layoutId per navbar variant to avoid cross-nav conflicts
  onHover: (label: string | null) => void;
  onClick: (link: NavLink) => void;
  activeLinkColor?: string;
}

export const DesktopLinks: React.FC<DesktopLinksProps> = ({
  links,
  activeLink,
  hoveredLink,
  layoutId,
  onHover,
  onClick,
  activeLinkColor = '#9CD5F0',
}) => (
  <div className="hidden md:flex items-center gap-10" role="list">
    {links.map((link) => {
      const isActive = (hoveredLink ?? activeLink) === link.label;
      return (
        <motion.button
          key={link.label}
          role="listitem"
          aria-label={`Navigate to ${link.label}`}
          aria-current={activeLink === link.label ? 'page' : undefined}
          onClick={() => onClick(link)}
          onMouseEnter={() => onHover(link.label)}
          onMouseLeave={() => onHover(null)}
          className="relative text-sm font-medium tracking-wide"
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          <span
            className="transition-colors duration-200"
            style={{ color: activeLink === link.label ? activeLinkColor : 'rgba(255,255,255,0.85)' }}
          >
            {link.label}
          </span>

          {isActive && (
            <motion.div
              layoutId={layoutId}
              className="absolute top-8 left-1/2 -translate-x-1/2 w-20 h-1 rounded-full"
              style={{ background: activeLinkColor }}
              transition={{ type: 'spring', stiffness: 380, damping: 30 }}
            />
          )}
        </motion.button>
      );
    })}
  </div>
);

// ─── CTA BUTTON ───────────────────────────────────────────────────────────────

interface CtaButtonProps {
  config: NavbarConfig;
  className?: string;
  style?: React.CSSProperties;
  glowColor?: string;
}

export const CtaButton: React.FC<CtaButtonProps> = ({
  config,
  className = '',
  style,
  glowColor = 'rgba(34,211,238,0.4)',
}) => {
  // Respect the ctaShow flag — render nothing if disabled
  if (!config.ctaShow) return null;

  // Fall back to siteConfig.primaryCtaHref when ctaHref is left empty
  const resolvedHref = config.ctaHref || siteConfig.primaryCtaHref;

  const handleClick = (e: React.MouseEvent<HTMLAnchorElement>) => {
    e.preventDefault();
    document.querySelector(resolvedHref)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  return (
    <motion.a
      href={resolvedHref}
      onClick={handleClick}
      whileHover={{ scale: 1.05, boxShadow: `0 0 22px ${glowColor}` }}
      whileTap={{ scale: 0.95 }}
      className={`hidden md:flex items-center font-medium text-sm transition-all duration-300 ${className}`}
      style={style}
      aria-label={`${config.ctaText} – CTA button`}
    >
      {config.ctaText}
    </motion.a>
  );
};

// ─── HAMBURGER BUTTON ─────────────────────────────────────────────────────────

interface HamburgerProps {
  isOpen: boolean;
  controls: string;
  onClick: () => void;
  className?: string;
}

export const Hamburger: React.FC<HamburgerProps> = ({ isOpen, controls, onClick, className = '' }) => (
  <motion.button
    whileTap={{ scale: 0.9 }}
    onClick={onClick}
    aria-expanded={isOpen}
    aria-controls={controls}
    aria-label={isOpen ? 'Close navigation menu' : 'Open navigation menu'}
    className={`md:hidden text-white p-2 ${className}`}
  >
    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d={isOpen ? 'M6 18L18 6M6 6l12 12' : 'M4 6h16M4 12h16M4 18h16'}
      />
    </svg>
  </motion.button>
);