// =============================================================================
//  Navbar.tsx — Main component
//  ⚠️  Do not edit this file. Customise via navbar.config.ts instead.
// =============================================================================

import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import navbarConfig from '../ConfigFiles/navbarConfig';
import siteConfig from '../ConfigFiles/siteConfig';
import type { NavLink } from '../ConfigFiles/navbarConfig';
import { Logo, DesktopLinks, CtaButton, Hamburger } from './NavbarComponents';

/** Pixels scrolled before the sticky bar slides in */
const SCROLL_THRESHOLD = 80;

/** Wait for mobile menu close animation before firing scrollIntoView */
const MENU_CLOSE_DELAY = 420;

const Navbar: React.FC = () => {
  // navLinks now live in siteConfig, shared with the footer and other components
  const { navLinks } = siteConfig;

  const [activeLink, setActiveLink]   = useState<string>(navLinks[0]?.label ?? '');
  const [hoveredLink, setHoveredLink] = useState<string | null>(null);
  const [isOpen, setIsOpen]           = useState<boolean>(false);
  const [isScrolled, setIsScrolled]   = useState<boolean>(false);

  const handleScroll = useCallback(() => {
    setIsScrolled(window.scrollY > SCROLL_THRESHOLD);
  }, []);

  useEffect(() => {
    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, [handleScroll]);

  const handleNavClick = (link: NavLink) => {
    setActiveLink(link.label);

    const scrollToTarget = () => {
      document.querySelector(link.href)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    };

    if (isOpen) {
      setIsOpen(false);
      setTimeout(scrollToTarget, MENU_CLOSE_DELAY);
    } else {
      scrollToTarget();
    }
  };

  return (
    <>
      {/* ── HERO PILL NAVBAR ─────────────────────────────────────────────── */}
      <header role="banner">
        <nav aria-label="Primary navigation" className="absolute top-4 left-0 right-0 z-50 px-4">

          <motion.div
            initial={{ y: -100, opacity: 0 }}
            animate={
              isScrolled
                ? { y: -100, opacity: 0, pointerEvents: 'none' as const }
                : { y: 0,    opacity: 1, pointerEvents: 'auto' as const }
            }
            transition={{ duration: 0.45, ease: 'easeInOut' }}
            className="max-w-[95%] mx-auto bg-white/20 rounded-full shadow-xl border border-gray-700"
          >
            <div className="flex items-center justify-between h-14">

              {/* Logo — reads siteConfig.logo internally */}
              <div className="ml-10">
                <Logo onClick={() => handleNavClick(navLinks[0])} />
              </div>

              {/* Desktop links */}
              <DesktopLinks
                links={navLinks}
                activeLink={activeLink}
                hoveredLink={hoveredLink}
                layoutId="pillActiveIndicator"
                onHover={setHoveredLink}
                onClick={handleNavClick}
                activeLinkColor="#9CD5F0"
              />

              {/* CTA */}
              <CtaButton
                config={navbarConfig}
                className="px-12 h-full bg-gradient-to-r from-blue-900 to-blue-950 text-white rounded-full shadow-lg shadow-blue-900/30 hover:shadow-cyan-500/40"
                glowColor="rgba(34,211,238,0.4)"
              />

              {/* Mobile hamburger */}
              <Hamburger
                isOpen={isOpen}
                controls="mobile-menu-pill"
                onClick={() => setIsOpen(!isOpen)}
                className="mr-4"
              />
            </div>
          </motion.div>

          {/* Pill navbar — mobile dropdown */}
          <motion.div
            id="mobile-menu-pill"
            role="menu"
            aria-label="Mobile navigation"
            initial={false}
            animate={isOpen && !isScrolled ? { height: 'auto', opacity: 1 } : { height: 0, opacity: 0 }}
            transition={{ duration: 0.4, ease: 'easeInOut' }}
            className="md:hidden overflow-hidden mx-4 bg-white/10 backdrop-blur-md rounded-3xl mt-2"
          >
            <div className="flex flex-col items-center gap-6 py-6">
              {navLinks.map((link) => (
                <motion.button
                  key={link.label}
                  role="menuitem"
                  onClick={() => handleNavClick(link)}
                  onMouseEnter={() => setHoveredLink(link.label)}
                  onMouseLeave={() => setHoveredLink(null)}
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  className="relative text-white text-sm font-medium"
                >
                  {link.label}
                  {hoveredLink === link.label && (
                    <motion.div
                      layoutId="mobileHoverLine"
                      className="absolute -bottom-2 left-0 h-[2px] w-full bg-[#9CD5F0] rounded-full"
                      initial={{ scaleX: 0 }}
                      animate={{ scaleX: 1 }}
                      exit={{ scaleX: 0 }}
                      transition={{ duration: 0.3, ease: 'easeOut' }}
                      style={{ transformOrigin: 'left' }}
                    />
                  )}
                </motion.button>
              ))}
            </div>
          </motion.div>

        </nav>
      </header>

      {/* ── STICKY SCROLL-TRIGGERED FULL-WIDTH NAVBAR ────────────────────── */}
      <AnimatePresence>
        {isScrolled && (
          <motion.nav
            key="sticky-nav"
            aria-label="Sticky navigation"
            role="navigation"
            initial={{ y: -80, opacity: 0 }}
            animate={{ y: 0,   opacity: 1 }}
            exit={{ y: -80,    opacity: 0 }}
            transition={{ duration: 0.4, ease: 'easeInOut' }}
            className="fixed top-0 left-0 right-0 z-50 w-full"
            style={{
              background: 'linear-gradient(135deg, #0a1628 0%, #0d1f3c 50%, #0a1628 100%)',
              borderBottom: '1px solid rgba(156, 213, 240, 0.15)',
              boxShadow: '0 4px 32px rgba(0, 0, 0, 0.4)',
            }}
          >
            <div className="max-w-7xl mx-auto px-6 flex items-center justify-between h-16">

              {/* Logo — reads siteConfig.logo internally */}
              <Logo onClick={() => handleNavClick(navLinks[0])} />

              {/* Desktop links */}
              <DesktopLinks
                links={navLinks}
                activeLink={activeLink}
                hoveredLink={hoveredLink}
                layoutId="stickyActiveIndicator"
                onHover={setHoveredLink}
                onClick={handleNavClick}
                activeLinkColor="#9CD5F0"
              />

              {/* CTA */}
              <CtaButton
                config={navbarConfig}
                className="px-12 h-2/3 bg-gradient-to-r from-blue-900 to-blue-950 text-white rounded-full shadow-lg shadow-blue-900/30 hover:shadow-cyan-500/40"
                glowColor="rgba(156,213,240,0.35)"
              />

              {/* Mobile hamburger */}
              <Hamburger
                isOpen={isOpen}
                controls="mobile-menu-sticky"
                onClick={() => setIsOpen(!isOpen)}
              />
            </div>

            {/* Sticky navbar — mobile dropdown */}
            <AnimatePresence>
              {isOpen && (
                <motion.div
                  id="mobile-menu-sticky"
                  role="menu"
                  aria-label="Mobile navigation"
                  key="sticky-mobile-menu"
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.35, ease: 'easeInOut' }}
                  className="md:hidden overflow-hidden border-t"
                  style={{
                    borderColor: 'rgba(156, 213, 240, 0.15)',
                    background: 'rgba(10, 22, 40, 0.98)',
                  }}
                >
                  <div className="flex flex-col items-center gap-6 py-6">
                    {navLinks.map((link) => (
                      <motion.button
                        key={link.label}
                        role="menuitem"
                        onClick={() => handleNavClick(link)}
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        className="text-white/85 text-sm font-medium transition-colors duration-200 hover:text-[#9CD5F0]"
                      >
                        {link.label}
                      </motion.button>
                    ))}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.nav>
        )}
      </AnimatePresence>
    </>
  );
};

export default Navbar;