// =============================================================================
//  AboutSection.tsx — About section
//  ⚠️  Do not edit this file. Customise via about.config.ts instead.
// =============================================================================

import { motion } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import { Check } from "lucide-react";
import aboutConfig from "../components/ConfigFiles/aboutConfig";

const AboutSection = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
          observer.disconnect(); 
        }
      },
      { threshold: 0.1 }
    );

    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  return (
    <section
      ref={sectionRef}
      id="about"
      role="region"
      aria-labelledby="about-heading"
      className="relative py-12 sm:py-16 md:py-20 bg-gradient-to-b from-[#1B3563] via-[#0d2444] to-[#020207] overflow-hidden"
    >
      {/* ── Centered content container ─────────────────────────────────────── */}
      <div className="max-w-7xl mx-auto px-8 sm:px-10 lg:px-2 relative">

        {/* ── Section header ────────────────────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isVisible ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mb-8 sm:mb-10 md:mb-12 text-center relative z-10"
        >
          <p
            className="text-cyan-400 text-xs sm:text-sm font-medium tracking-wider uppercase mb-3 sm:mb-4"
            aria-hidden="true"
          >
            {aboutConfig.sectionLabel}
          </p>
          <h2
            id="about-heading"
            className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-white px-4"
          >
            {aboutConfig.heading}
          </h2>
        </motion.div>

        {/* ── Two-column content grid ───────────────────────────────────────── */}
        <div className="grid lg:grid-cols-2 gap-6 sm:gap-8 lg:gap-12 relative">

          {/* ── Left column — team image ───────────────────────────────────── */}
          <motion.div
            initial={{ opacity: 0, x: -50 }}
            animate={isVisible ? { opacity: 1, x: 0 } : { opacity: 0, x: -50 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className="relative z-20"
          >
            <div className="relative rounded-xl sm:rounded-2xl overflow-hidden border border-cyan-500/30 sm:border-2 shadow-2xl shadow-cyan-500/20">
              <img
                src="./staff-working.png"
                alt={aboutConfig.imageAlt}
                className="w-full h-full object-cover aspect-video sm:aspect-4/3"
                loading="lazy"
                decoding="async"
              />
              {/* Decorative colour overlay */}
              <div
                className="absolute inset-0 bg-gradient-to-tr from-cyan-500/10 to-purple-500/10 pointer-events-none"
                aria-hidden="true"
              />
            </div>
          </motion.div>

          {/* ── Right column — text, features, stats ──────────────────────── */}
          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={isVisible ? { opacity: 1, x: 0 } : { opacity: 0, x: 50 }}
            transition={{ duration: 0.8, delay: 0.6 }}
            className="space-y-6 sm:space-y-8 relative z-20"
          >
            {/* Body paragraph */}
            <p className="text-gray-300 text-sm sm:text-base md:text-lg leading-relaxed">
              {aboutConfig.description}
            </p>

            {/* ── Feature bullet points ────────────────────────────────────── */}
            <ul
              className="grid grid-cols-2 gap-x-4 sm:gap-x-6 gap-y-2.5 sm:gap-y-3 list-none p-0 m-0"
              aria-label="Key features"
            >
              {aboutConfig.features.map((feature, index) => (
                <motion.li
                  key={index}
                  initial={{ opacity: 0, x: 20 }}
                  animate={isVisible ? { opacity: 1, x: 0 } : { opacity: 0, x: 20 }}
                  transition={{ duration: 0.5, delay: 0.8 + index * 0.1 }}
                  className="flex items-center gap-2 sm:gap-2.5 mb-6"
                >
                  {/* Decorative check icon */}
                  <div
                    className="flex-shrink-0 w-4 h-4 sm:w-5 sm:h-5 rounded-full bg-cyan-500/20 flex items-center justify-center"
                    aria-hidden="true"
                  >
                    <Check className="w-2.5 h-2.5 sm:w-3 sm:h-3 text-cyan-400" strokeWidth={3} />
                  </div>
                  <span className="text-gray-300 text-xs sm:text-sm md:text-base">
                    {feature}
                  </span>
                </motion.li>
              ))}
            </ul>

            {/* ── Stat cards ────────────────────────────────────────────────── */}
            <dl
              className="grid grid-cols-3 gap-2 sm:gap-3 md:gap-4"
              aria-label="Key statistics"
            >
              {aboutConfig.stats.map((stat, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  animate={isVisible ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
                  transition={{ duration: 0.6, delay: stat.delay + 0.6 }}
                  className="relative group"
                >
                  <div className="relative bg-gradient-to-br from-blue-900/40 to-blue-950/40 border border-cyan-500/30 rounded-lg sm:rounded-xl p-3 sm:p-4 md:p-6 hover:border-cyan-400/50 transition-all duration-300">

                    {/* Icon — decorative, aria-hidden */}
                    <div className="flex justify-center mb-1.5 sm:mb-2 md:mb-3" aria-hidden="true">
                      <div className="p-1.5 sm:p-2 bg-cyan-500/10 rounded-md sm:rounded-lg">
                        <stat.icon className="w-4 h-4 sm:w-5 sm:h-5 md:w-6 md:h-6 text-cyan-400" />
                      </div>
                    </div>

                    <div className="text-center">
                      {/* <dd> holds the prominent value */}
                      <dd className="text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold text-white mb-0.5 sm:mb-1 m-0">
                        {stat.value}
                      </dd>
                      {/* <dt> holds the descriptive label */}
                      <dt className="text-[10px] sm:text-xs text-gray-400 font-medium leading-tight">
                        {stat.label}
                      </dt>
                    </div>

                    {/* Hover glow overlay — decorative, locked */}
                    <div
                      className="absolute inset-0 bg-gradient-to-br from-cyan-500/0 to-purple-500/0 group-hover:from-cyan-500/5 group-hover:to-purple-500/5 rounded-lg sm:rounded-xl transition-all duration-300 pointer-events-none"
                      aria-hidden="true"
                    />
                  </div>
                </motion.div>
              ))}
            </dl>
          </motion.div>
        </div>
      </div>

      {/* ── Glass morphism panel ────────────────────────────────────────────── */}
      <motion.div
        initial={{ opacity: 0, x: "100%" }}
        animate={isVisible ? { opacity: 1, x: 0 } : { opacity: 0, x: "100%" }}
        transition={{ duration: 0.8 }}
        aria-hidden="true"
        className="hidden lg:block absolute top-12 right-0 h-[80vh] bg-slate-900/40 backdrop-blur-xl border-l border-slate-700/50 rounded-l-3xl shadow-2xl pointer-events-none"
        style={{
          background:      "rgba(15, 23, 42, 0.4)",
          backdropFilter:  "blur(20px)",
          width: "calc(66% + ((100% - min(1280px, 100%)) / 2) + 12.5%)",
        }}
      >
        {/* Inner glow — locked as part of template theme */}
        <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/5 via-transparent to-purple-500/5 rounded-l-3xl" />
      </motion.div>
    </section>
  );
};

export default AboutSection;