// =============================================================================
//  Footer.tsx — Site footer component
//  DO NOT edit this file. All customisation is done in:
//    - footer.config.ts   (footer-specific content)
//    - site.config.ts     (logo, brand name, nav links)
// =============================================================================

import { motion } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import LocationOnIcon  from '@mui/icons-material/LocationOn';
import EmailIcon       from '@mui/icons-material/Email';
import PhoneIcon       from '@mui/icons-material/Phone';
import InstagramIcon   from '@mui/icons-material/Instagram';
import LinkedInIcon    from '@mui/icons-material/LinkedIn';
import FacebookIcon    from '@mui/icons-material/Facebook';
import PinterestIcon   from '@mui/icons-material/Pinterest';

import siteConfig   from '../components/ConfigFiles/siteConfig';
import footerConfig from '../components/ConfigFiles/footerConfig';
import type { ContactItem, SocialLink } from '../components/ConfigFiles/footerConfig';

// ─── Icon maps (locked) ───────────────────────────────────────────────────────
// Maps platform/type strings from config to their MUI icon components.
// Adding new icons requires editing the component — by design, this keeps
// the icon set consistent with the template's visual language.

const SOCIAL_ICON_MAP: Record<SocialLink['platform'], React.ReactElement> = {
  instagram: <InstagramIcon fontSize="small" />,
  linkedin:  <LinkedInIcon  fontSize="small" />,
  facebook:  <FacebookIcon  fontSize="small" />,
  pinterest: <PinterestIcon fontSize="small" />,
};

const CONTACT_ICON_MAP: Record<ContactItem['type'], React.ReactElement> = {
  location: <LocationOnIcon sx={{ fontSize: 16 }} />,
  email:    <EmailIcon      sx={{ fontSize: 16 }} />,
  phone:    <PhoneIcon      sx={{ fontSize: 16 }} />,
};

// ─── Footer ───────────────────────────────────────────────────────────────────

/**
 * Footer
 *
 * 4-column layout:
 *   Col 1 — Brand (logo, description, social icons)  → from site.config + footer.config
 *   Col 2 — First link group                          → from footer.config.linkColumns[0]
 *   Col 3 — Second link group                         → from footer.config.linkColumns[1]
 *   Col 4 — Contact details                           → from footer.config.contactItems
 *
 * SEO notes:
 * - <footer> is a native HTML5 landmark — no role needed.
 * - aria-label distinguishes this footer from any other <footer> on the page.
 * - <nav> inside the footer with aria-label lets screen reader users jump
 *   directly to footer navigation via landmark navigation.
 * - Social links use <a> (not <button>) because they navigate to external pages.
 * - Contact email uses an href="mailto:" link so it opens the user's mail client.
 * - Contact phone uses an href="tel:" link for tap-to-call on mobile.
 * - Copyright year is computed dynamically in the config — never goes stale.
 */
const Footer = () => {
  const [isVisible, setIsVisible] = useState(false);
  const footerRef = useRef<HTMLElement>(null);

  // Trigger fade-in once the footer scrolls into view
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => entry.isIntersecting && setIsVisible(true),
      { threshold: 0.05 }
    );
    if (footerRef.current) observer.observe(footerRef.current);
    return () => observer.disconnect();
  }, []);

  return (
    <footer
      ref={footerRef}
      aria-label="Site footer"
      className="relative w-full bg-[#06101f] border-t border-white/5 px-6 pt-14 pb-8"
    >
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        animate={isVisible ? { opacity: 1, y: 0 } : {}}
        transition={{ duration: 0.7, ease: 'easeOut' }}
        className="max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-12"
      >

        {/* ── Col 1: Brand ─────────────────────────────────────────────────── */}
        <div className="flex flex-col gap-5">

          {/* Logo — pulled from site.config so it stays in sync with the navbar */}
          <a href="#home" aria-label={`${siteConfig.brandName} — go to top`} className="block w-40">
            {siteConfig.logo.src ? (
              <img
                src={siteConfig.logo.src}
                alt={siteConfig.logo.alt}
                className="w-full h-auto object-contain"
                width={160}
                height={48}
                loading="lazy"
                decoding="async"
              />
            ) : (
              <span className="text-white font-bold text-lg">{siteConfig.logo.text}</span>
            )}
          </a>

          {/* Brand description */}
          <p className="text-gray-400 text-sm leading-relaxed max-w-[220px]">
            {footerConfig.brandDescription}
          </p>

          {/* Social icons */}
          <div className="flex items-center gap-3 mt-1" role="list" aria-label="Social media links">
            {footerConfig.socialLinks.map(({ id, label, href, platform }) => (
              <a
                key={id}
                href={href}
                aria-label={label}
                target="_blank"
                rel="noopener noreferrer" // required for security with target="_blank"
                role="listitem"
                className="
                  w-9 h-9 rounded-full border border-white/15
                  flex items-center justify-center text-gray-400
                  hover:text-white hover:border-white/40
                  transition-colors duration-200
                "
              >
                {SOCIAL_ICON_MAP[platform]}
              </a>
            ))}
          </div>
        </div>

        {/* ── Col 2 & 3: Link columns ───────────────────────────────────────── */}
        {footerConfig.linkColumns.map((column) => {
          const isExternal = (href: string) => href.startsWith('http');
          const isAnchor   = (href: string) => href.startsWith('#');

          return (
            /*
             * <nav> makes each link column a navigable landmark.
             * aria-label distinguishes them (e.g. "Product links", "Company links").
             */
            <nav key={column.heading} aria-label={`${column.heading} links`}>
              <h4 className="text-white font-semibold text-sm mb-5">
                {column.heading}
              </h4>
              <ul className="flex flex-col gap-4">
                {column.links.map(({ label, href }) => (
                  <li key={label}>
                    <a
                      href={href}
                      {...(isExternal(href)
                        ? { target: '_blank', rel: 'noopener noreferrer' }
                        : {}
                      )}
                      onClick={
                        isAnchor(href)
                          ? (e) => {
                              // Smooth-scroll for internal anchor links
                              e.preventDefault();
                              document.querySelector(href)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
                            }
                          : undefined
                      }
                      className="text-gray-400 text-sm hover:text-white transition-colors duration-200"
                    >
                      {label}
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
          );
        })}

        {/* ── Col 4: Contact ───────────────────────────────────────────────── */}
        <div className="flex flex-col gap-5">
          <h4 className="text-white font-semibold text-sm mb-1">Contact Us</h4>

          {footerConfig.contactItems.map(({ id, label, value, type }) => {
            /*
             * Email and phone use semantic href values so browsers can
             * open the mail client or dialler natively on click.
             * Location has no href — it is just informational text.
             */
            const href =
              type === 'email'    ? `mailto:${value}`            :
              type === 'phone'    ? `tel:${value.replace(/\s/g, '')}` :
              undefined;

            return (
              <div key={id} className="flex items-start gap-3">
                {/* Icon badge */}
                <div
                  aria-hidden="true"
                  className="w-8 h-8 rounded-full bg-blue-900/40 border border-blue-500/20 flex items-center justify-center text-blue-400 flex-shrink-0 mt-0.5"
                >
                  {CONTACT_ICON_MAP[type]}
                </div>

                <div>
                  <p className="text-gray-400 text-xs mb-0.5">{label}</p>

                  {/*
                   * Multi-line values (e.g. address) are split on \n and
                   * each line rendered as its own <p>.
                   * Email and phone wrap in an <a> for interactivity.
                   */}
                  {href ? (
                    <a
                      href={href}
                      className="text-white text-sm hover:text-cyan-400 transition-colors duration-200"
                    >
                      {value}
                    </a>
                  ) : (
                    value.split('\n').map((line) => (
                      <p key={line} className="text-white text-sm">{line}</p>
                    ))
                  )}
                </div>
              </div>
            );
          })}
        </div>

      </motion.div>

      {/* ── Copyright bar ─────────────────────────────────────────────────── */}
      <div className="max-w-6xl mx-auto mt-12 pt-6 border-t border-white/5">
        <p className="text-gray-500 text-xs text-center">
          {footerConfig.copyright}
        </p>
      </div>
    </footer>
  );
};

export default Footer;