// =============================================================================
//  HowItWorksSection.tsx — "How It Works" section
//  ⚠️  Do not edit this file. Customise text via howitworks.config.ts.
// =============================================================================

import { motion } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import howItWorksConfig from "../components/ConfigFiles/howitworksConfig";

// ─── LOCKED THEME CONSTANTS ───────────────────────────────────────────────────
// SVG path that defines the animated line connecting the three steps.
// Locked: changing this breaks the alignment of the step node circles.
const PATH_DATA =
  "M -100 30 L 10 100 L 130 100 L 250 10 L 350 10 L 380 200 L 600 280 L 670 120 L 720 150 L 800 80 L 830 170 L 1200 30";

// Pixel coordinates (in the 1000×350 SVG viewBox) where each step node sits.
// Locked: must stay in sync with PATH_DATA waypoints.
const STEP_NODES = [
  { cx: 130, cy: 100, color: "#06b6d4" }, // Step 1 — cyan
  { cx: 380, cy: 200, color: "#8b5cf6" }, // Step 2 — violet
  { cx: 830, cy: 165, color: "#a855f7" }, // Step 3 — purple
] as const;

// Delay (ms) after the section becomes visible before the path animation fires.
const ANIMATION_START_DELAY = 500;

// ─── COMPONENT ────────────────────────────────────────────────────────────────

const HowItWorksSection = () => {
  // `isVisible`        — true once section enters viewport; triggers text fade-ins.
  // `animationStarted` — true shortly after isVisible; triggers SVG path draw.
  const [isVisible, setIsVisible]           = useState(false);
  const [animationStarted, setAnimationStarted] = useState(false);
  const sectionRef                          = useRef<HTMLDivElement>(null);

  // IntersectionObserver — fires entrance animations on first scroll-into-view.
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
          setTimeout(() => setAnimationStarted(true), ANIMATION_START_DELAY);
        }
      },
      { threshold: 0.3 }
    );
    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  const { heading, subtext, steps } = howItWorksConfig;

  return (
    // `id` must match the href used for this section in navbar.config.ts.
    <section
      ref={sectionRef}
      id="how-it-works"
      aria-labelledby="hiw-heading"
      className="relative py-16 sm:py-20 md:py-24 lg:py-26 bg-black overflow-hidden"
    >
      {/* ── CONTENT ────────────────────────────────────────────────────────── */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">

        {/* Section header
            — "HOW IT WORKS" eyebrow is locked (template branding).
            — heading and subtext come from howitworks.config.ts. */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isVisible ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="text-center lg:mb-20 sm:mb-0 md:mb-2"
        >
          {/* Eyebrow label — locked */}
          <p
            className="text-cyan-400 text-xs sm:text-sm font-medium tracking-wider uppercase mb-3 sm:mb-4"
            aria-hidden="true" // decorative; h2 provides the accessible section name
          >
            HOW IT WORKS
          </p>

          {/* Section heading — h2 since this is below the page h1 */}
          <h2
            id="hiw-heading"
            className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-4 sm:mb-6 px-4"
          >
            {heading}
          </h2>

          <p className="text-gray-300 text-sm sm:text-base md:text-lg max-w-4xl mx-auto px-4">
            {subtext}
          </p>
        </motion.div>

        {/* ── MOBILE STEP LIST (visible below sm breakpoint) ─────────────────
            Simple stacked layout — the SVG animation is hidden on mobile. */}
        <ol
          className="block sm:hidden space-y-12 pb-8"
          aria-label="Steps to get started"
        >
          {steps.map((step, index) => {
            const node = STEP_NODES[index];
            // Stagger: 0.8s base + 0.4s per step
            const delay = 0.8 + index * 0.4;
            const xDir  = index === 1 ? 0 : index === 0 ? -30 : 30; // left / centre / right entrance

            return (
              <li key={step.title}>
                <motion.div
                  initial={{ opacity: 0, x: xDir, y: index === 1 ? 30 : 0 }}
                  animate={
                    isVisible
                      ? { opacity: 1, x: 0, y: 0 }
                      : { opacity: 0, x: xDir, y: index === 1 ? 30 : 0 }
                  }
                  transition={{ duration: 0.6, delay }}
                  className="flex flex-col items-center text-center"
                >
                  {/* Step number */}
                  <div
                    className="text-7xl font-bold text-white/20 leading-none mb-2"
                    aria-hidden="true"
                  >
                    {index + 1}
                  </div>

                  {/* Step colour dot — locked */}
                  <div
                    className="w-3 h-3 rounded-full mb-4"
                    style={{ background: node.color }}
                    aria-hidden="true"
                  />

                  <h3 className="text-lg sm:text-xl font-bold text-white mb-2">
                    {step.title}
                  </h3>
                  <p className="text-sm sm:text-base text-gray-300 leading-relaxed max-w-sm">
                    {step.description}
                  </p>
                </motion.div>

                {/* Connector line between steps — not shown after the last step */}
                {index < steps.length - 1 && (
                  <div className="flex justify-center mt-12" aria-hidden="true">
                    <div
                      className="w-px h-10"
                      style={{
                        background: `linear-gradient(to bottom, ${node.color}, ${STEP_NODES[index + 1].color})`,
                      }}
                    />
                  </div>
                )}
              </li>
            );
          })}
        </ol>
      </div>

      {/* ── DESKTOP SVG LAYOUT (visible from sm breakpoint up) ─────────────────
          The animated path, travelling ball, and step content blocks.
          Locked: all SVG coordinates and colors are part of the template theme. */}
      <div className="hidden sm:block" aria-hidden="true">
        <div className="relative w-full h-[500px] sm:h-[600px] md:h-[650px] lg:h-[450px]">

          {/* SVG canvas — path, nodes, ripples, travelling ball */}
          <svg
            className="absolute inset-0 w-full h-full"
            viewBox="0 0 1000 350"
            preserveAspectRatio="xMidYMid meet"
            focusable="false"
          >
            <defs>
              {/* Gradient along the connecting path — locked */}
              <linearGradient id="lineGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%"   stopColor="#06b6d4" />
                <stop offset="50%"  stopColor="#8b5cf6" />
                <stop offset="100%" stopColor="#a855f7" />
              </linearGradient>
            </defs>

            {/* Animated connecting path */}
            <motion.path
              d={PATH_DATA}
              fill="none"
              stroke="url(#lineGradient)"
              strokeWidth="4"
              strokeLinecap="round"
              strokeLinejoin="round"
              initial={{ pathLength: 0 }}
              animate={animationStarted ? { pathLength: 1 } : { pathLength: 0 }}
              transition={{ duration: 2.5, ease: "easeInOut" }}
            />

            {/* Static node circles at each step waypoint */}
            {STEP_NODES.map((node) => (
              <circle
                key={`node-${node.cx}`}
                cx={node.cx}
                cy={node.cy}
                r="10"
                fill={node.color}
                className="drop-shadow-lg"
              />
            ))}

            {/* Ripple rings at each node — two offset rings per node for depth */}
            {animationStarted &&
              STEP_NODES.map((node, i) =>
                [0, 0.5].map((offset) => (
                  <motion.circle
                    key={`ripple-${node.cx}-${offset}`}
                    cx={node.cx}
                    cy={node.cy}
                    r="10"
                    fill="none"
                    stroke={node.color}
                    strokeWidth="2"
                    initial={{ r: 10, opacity: 0.8 }}
                    animate={{ r: 30, opacity: 0 }}
                    transition={{
                      duration: 1.5,
                      repeat: Infinity,
                      repeatDelay: 0.5,
                      delay: 1 + i * 0.5 + offset,
                    }}
                  />
                ))
              )}

            {/* Travelling white ball that follows the path */}
            {animationStarted && (
              <motion.circle
                r="7"
                fill="#ffffff"
                className="drop-shadow-[0_0_12px_rgba(255,255,255,0.9)]"
                initial={{ opacity: 0 }}
                animate={{ opacity: [0, 1, 1, 1, 1] }}
                transition={{ duration: 2 }}
              >
                <animateMotion dur="5s" repeatCount="indefinite" path={PATH_DATA} />
              </motion.circle>
            )}
          </svg>

          {/* ── STEP CONTENT BLOCKS ─────────────────────────────────────────────
              Absolutely positioned to align with their SVG node.
              Positions are locked to match PATH_DATA waypoints. */}

          {/* Step 1 — top-left */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={isVisible ? { opacity: 1, x: 0 } : { opacity: 0, x: -30 }}
            transition={{ duration: 0.6, delay: 0.8 }}
            className="absolute top-[34%] sm:top-[10%] md:top-[12%] lg:top-[18%] left-0 sm:left-[2%] md:left-[4%] lg:left-[8%] max-w-[260px] sm:max-w-[280px] md:max-w-xs"
            style={{ zIndex: 20 }}
          >
            <div className="relative">
              <div className="text-[70px] sm:text-[80px] md:text-[100px] lg:text-[120px] font-bold text-white/30 absolute lg:-top-20 md:top-18 sm:top-24 lg:left-22 md:left-8 sm:left-10 pointer-events-none leading-none">
                1
              </div>
              <div className="absolute lg:top-20 sm:top-52 lg:left-10 sm:left-6 lg:w-[30ch] sm:w-[20ch] text-center">
                <h3 className="text-base sm:text-md md:text-xl lg:text-2xl font-bold text-white mb-2 sm:mb-3">
                  {steps[0].title}
                </h3>
                <p className="text-xs sm:text-sm md:text-base text-gray-300 leading-relaxed">
                  {steps[0].description}
                </p>
              </div>
            </div>
          </motion.div>

          {/* Step 2 — centre-bottom */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={isVisible ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
            transition={{ duration: 0.6, delay: 1.2 }}
            className="absolute top-[35%] sm:top-[40%] md:top-[45%] lg:top-[58%] left-[50%] transform -translate-x-1/2 max-w-[260px] sm:max-w-[280px] md:max-w-xs"
            style={{ zIndex: 20 }}
          >
            <div className="relative">
              <div className="text-[70px] sm:text-[80px] md:text-[100px] lg:text-[120px] font-bold text-white/30 absolute lg:top-4 md:top-16 sm:top-22 lg:-left-28 sm:-left-12 transform -translate-x-1/2 pointer-events-none leading-none">
                2
              </div>
              <div className="absolute lg:-top-50 md:-top-60 sm:-top-36 lg:-left-28 sm:-left-18 lg:w-[30ch] sm:w-[18ch] text-center">
                <h3 className="text-base sm:text-sm md:text-xl lg:text-2xl font-bold text-white mb-2 sm:mb-3">
                  {steps[1].title}
                </h3>
                <p className="text-xs sm:text-sm md:text-base text-gray-300 leading-relaxed">
                  {steps[1].description}
                </p>
              </div>
            </div>
          </motion.div>

          {/* Step 3 — top-right */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={isVisible ? { opacity: 1, x: 0 } : { opacity: 0, x: 30 }}
            transition={{ duration: 0.6, delay: 1.6 }}
            className="absolute top-[62%] sm:top-[68%] md:top-[72%] lg:top-[18%] right-0 sm:right-[2%] md:right-[4%] lg:right-[8%] max-w-[260px] sm:max-w-[280px] md:max-w-xs"
            style={{ zIndex: 20 }}
          >
            <div className="relative">
              <div className="text-[70px] sm:text-[80px] md:text-[100px] lg:text-[120px] font-bold text-white/30 absolute lg:-top-4 md:-top-66 sm:-top-52 lg:right-36 md:right-12 sm:right-14 pointer-events-none leading-none">
                3
              </div>
              <div className="absolute lg:top-42 md:-top-30 sm:-top-24 lg:-left-74 sm:-left-48 lg:w-[30ch] sm:w-[18ch] text-center">
                <h3 className="text-base sm:text-sm md:text-xl lg:text-2xl font-bold text-white mb-2 sm:mb-3">
                  {steps[2].title}
                </h3>
                <p className="text-xs sm:text-sm md:text-base text-gray-300 leading-relaxed">
                  {steps[2].description}
                </p>
              </div>
            </div>
          </motion.div>

        </div>
      </div>
    </section>
  );
};

export default HowItWorksSection;