// =============================================================================
//  Newsletter.tsx — Newsletter / email capture section
//  DO NOT edit this file. All customisation is done in newsletter.config.ts
// =============================================================================

import { motion, useScroll, useTransform } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import newsletterConfig from '../components/ConfigFiles/newsletterConfig';

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Basic email format validation.
 * Checks for the pattern: characters @ characters . characters
 * This is intentionally lightweight — the browser's type="email" handles
 * deeper validation. This just prevents obviously empty or malformed strings.
 */
const isValidEmail = (value: string): boolean =>
  /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim());

// ─── Main component ───────────────────────────────────────────────────────────

const Newsletter = () => {
  const { heading, subheading, inputPlaceholder, errorMessage, successMessage, submitHref } =
    newsletterConfig;

  const [email,      setEmail]      = useState('');
  const [error,      setError]      = useState('');    // inline error message
  const [submitted,  setSubmitted]  = useState(false); // success state
  const [isVisible,  setIsVisible]  = useState(false);

  const sectionRef = useRef<HTMLDivElement>(null);
  const inputRef   = useRef<HTMLInputElement>(null);

  // ── Intersection observer: trigger fade-in animation on scroll into view
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => entry.isIntersecting && setIsVisible(true),
      { threshold: 0.1 }
    );
    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  // ── Parallax: background image scrolls at 40% of the page scroll speed
  const { scrollYProgress } = useScroll({
    target:  sectionRef,
    offset: ['start end', 'end start'],
  });
  const bgY = useTransform(scrollYProgress, [0, 1], ['-20%', '20%']);

  /**
   * handleSubmit
   *
   * 1. Validates the email field — shows an error and focuses the input if empty.
   * 2. On valid email:
   *    - Shows the success message briefly.
   *    - Navigates to submitHref (default: '#home', scrolls to top of page).
   *
   * TO CONNECT A NEWSLETTER PROVIDER:
   *   Replace the contents of this function (after the validation block) with
   *   your API call, e.g.:
   *
   *   await fetch('https://api.your-provider.com/subscribe', {
   *     method:  'POST',
   *     headers: { 'Content-Type': 'application/json' },
   *     body:    JSON.stringify({ email }),
   *   });
   *
   *   Then redirect to a thank-you page:
   *   window.location.href = submitHref;
   */
  const handleSubmit = () => {
    // ── Validation ────────────────────────────────────────────────────────────
    if (!isValidEmail(email)) {
      setError(errorMessage);
      inputRef.current?.focus(); // return focus to input for keyboard/screen-reader users
      return;
    }

    // ── Success ───────────────────────────────────────────────────────────────
    setError('');
    setSubmitted(true);

    // Give the user a moment to read the success message before navigating
    setTimeout(() => {
      const isExternal = submitHref.startsWith('http');
      if (isExternal) {
        window.location.href = submitHref;
      } else {
        // Internal anchor — smooth scroll
        const target = document.querySelector(submitHref);
        if (target) {
          target.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
        // Reset form after navigation so it's clean if the user scrolls back
        setTimeout(() => {
          setEmail('');
          setSubmitted(false);
        }, 800);
      }
    }, 1500);
  };

  return (
    <section
      ref={sectionRef}
      id="subscribe"                        // matched by navbar + CTA links — do not rename
      aria-labelledby="newsletter-heading"
      className="relative w-full overflow-hidden"
      style={{ minHeight: '340px' }}
    >
      {/* ── Parallax background image ────────────────────────────────────────
          aria-hidden + empty alt: purely decorative, adds no meaning.
          The dark overlay below ensures text stays legible at all times.     */}
      <motion.div
        className="absolute inset-0 w-full h-full"
        style={{ y: bgY, scale: 1.15 }}
        aria-hidden="true"
      >
        <img
          src="./newsletter-img.png"
          alt=""
          className="w-full h-full object-cover object-center"
          loading="eager"   // in viewport on most screens — do not lazy-load
          decoding="async"
        />
      </motion.div>

      {/* Dark overlay — ensures text contrast over the photo */}
      <div className="absolute inset-0 bg-[#0a1628]/70" aria-hidden="true" />

      {/* ── Content ── */}
      <motion.div
        initial={{ opacity: 0, y: 28 }}
        animate={isVisible ? { opacity: 1, y: 0 } : {}}
        transition={{ duration: 0.7, ease: 'easeOut' }}
        className="relative z-10 flex flex-col items-center justify-center text-center px-4 py-20"
      >
        {/* Decorative eyebrow label — aria-hidden */}
        <p
          aria-hidden="true"
          className="text-white/80 text-xs font-semibold tracking-[0.25em] uppercase mb-4"
        >
          NEWSLETTER
        </p>

        {/*
         * <h2> — accessible section label, linked via aria-labelledby above.
         * Content from config so clients can rename it freely.
         */}
        <h2
          id="newsletter-heading"
          className="text-white text-3xl sm:text-4xl lg:text-5xl font-bold mb-5 max-w-2xl leading-tight"
        >
          {heading}
        </h2>

        <p className="text-gray-300 text-sm sm:text-base max-w-xl mb-10 leading-relaxed">
          {subheading}
        </p>

        {/* ── Email form ───────────────────────────────────────────────────────
            Using a <form> element so:
            - Browsers offer email autocomplete natively
            - Enter key submits without extra JS
            - Screen readers announce this as a form landmark                  */}
        <form
          onSubmit={(e) => { e.preventDefault(); handleSubmit(); }}
          noValidate // we handle validation ourselves for a consistent UI
          className="w-full max-w-md"
          aria-label="Newsletter subscription form"
        >
          <div className="flex items-center gap-3 w-full">

            {/* Email input with gradient border */}
            <div
              className="flex-1 p-[1.5px] rounded-full"
              style={{ background: 'linear-gradient(135deg, #c084fc 0%, #9CD5F0 100%)' }}
            >
              <div className="flex items-center bg-[#0d1b35] rounded-full px-5 py-3">
                <label htmlFor="newsletter-email" className="sr-only">
                  Email address
                </label>
                <input
                  ref={inputRef}
                  id="newsletter-email"
                  type="email"
                  value={email}
                  onChange={(e) => {
                    setEmail(e.target.value);
                    // Clear the error as soon as the user starts correcting it
                    if (error) setError('');
                  }}
                  placeholder={inputPlaceholder}
                  aria-describedby={error ? 'newsletter-error' : undefined}
                  aria-invalid={!!error}
                  autoComplete="email"
                  className="flex-1 bg-transparent text-white text-sm placeholder-gray-400 outline-none border-none"
                />
              </div>
            </div>

            {/* Submit button */}
            <button
              type="submit"
              aria-label="Subscribe to newsletter"
              className="flex-shrink-0 w-12 h-12 rounded-2xl flex items-center justify-center transition-opacity duration-200 hover:opacity-80 active:scale-95"
              style={{ background: 'linear-gradient(135deg, #c084fc 0%, #9CD5F0 100%)' }}
            >
              {/* Paper-plane send icon — decorative, aria-hidden */}
              <svg
                viewBox="0 0 24 24"
                className="w-5 h-5 text-white"
                fill="none"
                stroke="currentColor"
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <line x1="22" y1="2" x2="11" y2="13" />
                <polygon points="22 2 15 22 11 13 2 9 22 2" />
              </svg>
            </button>
          </div>

          {/* ── Inline feedback messages ──────────────────────────────────────
              Only one of error or success is shown at a time.
              role="alert" + aria-live="polite" announces the message to
              screen readers without interrupting what they were reading.      */}

          {error && !submitted && (
            <p
              id="newsletter-error"
              role="alert"
              aria-live="polite"
              className="mt-3 text-red-400 text-xs text-center"
            >
              {error}
            </p>
          )}

          {submitted && (
            <p
              role="status"
              aria-live="polite"
              className="mt-3 text-cyan-400 text-xs text-center"
            >
              {successMessage}
            </p>
          )}
        </form>
      </motion.div>
    </section>
  );
};

export default Newsletter;