// =============================================================================
//  PricingPlans.tsx — Pricing plans section component
//  DO NOT edit this file. All customisation is done in pricing.config.ts
// =============================================================================

import { motion } from 'framer-motion';
import React, { useEffect, useRef, useState } from 'react';
const CheckCircleIcon = React.lazy(() => import('@mui/icons-material/CheckCircle'))
import pricingConfig from '../components/ConfigFiles/pricingConfig';
import type { PricingPlan } from '../components/ConfigFiles/pricingConfig';

// ─── PlanCard sub-component ───────────────────────────────────────────────────

const PlanCard = ({
  plan,
  index,
  isVisible,
  billingLabel,
}: {
  plan:         PricingPlan;
  index:        number;
  isVisible:    boolean;
  billingLabel: string;
}) => {
  const { highlighted } = plan;

  // Determine if the CTA href is an external URL or an internal anchor
  const isExternal = plan.ctaHref.startsWith('http');

  return (
    <motion.article
      initial={{ opacity: 0, y: 40 }}
      animate={isVisible ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.6, delay: 0.15 + index * 0.12, ease: 'easeOut' }}
      whileHover={{ scale: 1.05 }}
      aria-label={`${plan.name} plan — $${plan.price}${billingLabel}`}
      itemScope
      itemType="https://schema.org/Offer"
      className={`
        relative flex flex-col rounded-2xl p-6 w-full max-w-sm
        border transition-colors duration-300
        ${
          highlighted
            ? 'bg-gradient-to-b from-[#020207]/80 to-[#1B3563]/80 border-blue-500/40 shadow-[0_0_40px_rgba(59,130,246,0.12)] hover:cursor-pointer'
            : 'bg-gradient-to-b from-[#020207]/80 to-[#1B3563]/80 border-white/10 hover:border-white/20 hover:cursor-pointer'
        }
      `}
    >
      {/* Plan icon */}
      <div className="mb-4">
        <img
          src={plan.icon}
          alt="" // decorative — the plan name in the <h3> already identifies this card
          aria-hidden="true"
          width={40}
          height={40}
          className="w-10 h-10 object-contain"
          loading="lazy"
          decoding="async"
        />
      </div>

      {/* Plan name + subtitle */}
      <h3
        className="text-white font-bold text-xl mb-1"
        itemProp="name"
      >
        {plan.name}
      </h3>
      <p className="text-gray-400 text-sm mb-5">
        {plan.subtitle}
      </p>

      {/* Price — Schema.org marks up the price and currency for rich results */}
      <div
        className="flex items-baseline gap-2 mb-6"
        itemProp="priceSpecification"
        itemScope
        itemType="https://schema.org/UnitPriceSpecification"
      >
        <meta itemProp="priceCurrency" content="USD" />
        <meta itemProp="price"         content={String(plan.price)} />
        <span className="text-5xl font-extrabold text-[#7B6FEE]" aria-label={`$${plan.price}`}>
          ${plan.price}
        </span>
        <span className="text-gray-400 text-sm" aria-hidden="true">
          {billingLabel}
        </span>
      </div>

      {/* Features list */}
      <div className="flex-1 bg-[#D9D9D9]/20 rounded-xl p-4 mb-6">
        <p className="text-white text-sm font-semibold mb-3">Features</p>
        <ul
          className="space-y-2"
          aria-label={`${plan.name} plan features`}
        >
          {plan.features.map((feat) => (
            <li
              key={feat}
              className="flex items-center gap-2 text-gray-300 text-sm"
              itemProp="description"
            >
              {/* Icon is decorative — the text already communicates the feature */}
              <CheckCircleIcon
                sx={{ fontSize: 16, color: '#60a5fa' }}
                aria-hidden={true}
              />
              {feat}
            </li>
          ))}
        </ul>
      </div>

      {/*
       * CTA — <a> not <button> because it navigates to a destination.
       *
       * While building:   ctaHref="#subscribe" → scrolls to contact form
       * After going live: ctaHref="https://buy.stripe.com/..." → opens checkout
       *
       * External links open in a new tab. rel="noopener noreferrer" is required
       * for security when using target="_blank".
       */}
      <a
        href={plan.ctaHref}
        {...(isExternal
          ? { target: '_blank', rel: 'noopener noreferrer' }
          : {
              onClick: (e) => {
                // Internal anchor — smooth scroll instead of jumping
                e.preventDefault();
                document.querySelector(plan.ctaHref)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
              },
            }
        )}
        aria-label={`Choose the ${plan.name} plan`}
        itemProp="url"
        className="
          w-full py-3 rounded-xl font-semibold text-white text-sm text-center
          bg-gradient-to-r from-blue-600 to-blue-500
          hover:from-blue-500 hover:to-blue-400
          active:scale-95
          transition-all duration-200 shadow-lg shadow-blue-900/30
          cursor-pointer block
        "
      >
        Choose Plan
      </a>
    </motion.article>
  );
};

// ─── Main PricingPlans component ──────────────────────────────────────────────

const PricingPlans = () => {
  const { heading, billingLabel, plans } = pricingConfig;

  const [isVisible, setIsVisible] = useState(false);
  const sectionRef = useRef<HTMLDivElement>(null);

  // Reveal cards once the section scrolls into view
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => entry.isIntersecting && setIsVisible(true),
      { threshold: 0.1 }
    );
    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  return (
    <section
      ref={sectionRef}
      id="pricing-plans"
      aria-labelledby="pricing-heading"
      itemScope
      itemType="https://schema.org/OfferCatalog"
      className="relative w-full bg-[#020408] overflow-hidden px-4 mt-24"
    >
      {/* Decorative background image — hidden from assistive tech */}
      <div className="absolute -inset-40 opacity-90" aria-hidden="true">
        <div
          className="absolute -inset-40"
          style={{ backgroundImage: 'url("./bg-image.webp")' }}
        />
      </div>

      {/* Section header */}
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        animate={isVisible ? { opacity: 1, y: 0 } : {}}
        transition={{ duration: 0.7 }}
        className="relative z-10 text-center mb-14"
      >
        {/* Decorative eyebrow label — aria-hidden, the h2 is the real section label */}
        <p
          aria-hidden="true"
          className="text-cyan-400 text-xs sm:text-sm font-medium tracking-wider uppercase mb-3 sm:mb-4"
        >
          PRICING PLANS
        </p>

        <h2
          id="pricing-heading"
          className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-4 sm:mb-6 px-4"
          itemProp="name"
        >
          {heading}
        </h2>
      </motion.div>

      {/* Cards row */}
      <div className="relative z-10 flex flex-col sm:flex-row items-center justify-center gap-6 max-w-5xl mx-auto mb-10">
        {plans.map((plan, i) => (
          <PlanCard
            key={plan.id}
            plan={plan}
            index={i}
            isVisible={isVisible}
            billingLabel={billingLabel}
          />
        ))}
      </div>
    </section>
  );
};

export default PricingPlans;