// =============================================================================
//  Services.tsx — Services section
//  ⚠️  Do not edit this file. Customise text and icons via services.config.ts.
// =============================================================================

import { motion } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import servicesConfig from "../components/ConfigFiles/servicesConfig";

// ─── ANIMATION CONSTANTS ──────────────────────────────────────────────────────
// Stagger delay between each card's entrance animation (seconds).
const CARD_STAGGER = 0.1;

// Spring config for the card slide-up on hover.
const HOVER_SPRING = { type: "spring", stiffness: 300, damping: 30 } as const;

// ─── COMPONENT ────────────────────────────────────────────────────────────────

const Services = () => {
  // Tracks whether the section has entered the viewport so entrance
  // animations only fire once the user scrolls to this section.
  const [isVisible, setIsVisible]     = useState(false);
  const [hoveredCard, setHoveredCard] = useState<number | null>(null);
  const sectionRef                    = useRef<HTMLDivElement>(null);

  // IntersectionObserver — trigger entrance animations on scroll-into-view.
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setIsVisible(true); },
      { threshold: 0.1 }
    );
    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  const { heading, subtext, cards } = servicesConfig;

  return (
    // `id="services"` must match the href in navbar.config.ts for scroll-nav to work.
    <section
      ref={sectionRef}
      id="services"
      aria-labelledby="services-heading"
      className="relative py-10 sm:py-10 md:py-10 bg-[#020207] overflow-hidden"
    >

      {/* ── BACKGROUND ─────────────────────────────────────────────────────────
          Locked: part of the template theme. Do not modify. */}
      <div className="absolute inset-0 opacity-70" aria-hidden="true">
        <div
          className="absolute inset-0"
          style={{ backgroundImage: `url("./bg-image.png")` }}
        />
      </div>

      {/* ── CONTENT ────────────────────────────────────────────────────────── */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">

        {/* Section header
            — "OUR SERVICES" eyebrow label is locked (template branding).
            — heading and subtext come from services.config.ts. */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isVisible ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="text-center mb-12 sm:mb-16"
        >
          {/* Eyebrow label — locked */}
          <p
            className="text-cyan-400 text-xs sm:text-sm font-medium tracking-wider uppercase mb-3 sm:mb-4"
            aria-hidden="true" // decorative; screen readers get context from h2
          >
            OUR SERVICES
          </p>

          {/* Section heading — SEO: use h2 as this sits below the page h1 */}
          <h2
            id="services-heading"
            className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-4 sm:mb-6 px-4"
          >
            {heading}
          </h2>

          <p className="text-gray-300 text-sm sm:text-base md:text-lg max-w-3xl mx-auto px-4">
            {subtext}
          </p>
        </motion.div>

        {/* Service cards grid
            — Uses a wrapping flex row so odd card counts stay centred.
            — Card count and content come from services.config.ts. */}
        <ul
          className="flex flex-wrap justify-center gap-6 sm:gap-8 lg:gap-10 max-w-6xl mx-auto"
          aria-label="Services offered"
        >
          {cards.map((service, index) => (
            <motion.li
              key={service.title}
              initial={{ opacity: 0, y: 30 }}
              animate={isVisible ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
              transition={{ duration: 0.6, delay: index * CARD_STAGGER + 0.1 }}
              className="w-full sm:w-[48%] lg:w-[31%] max-w-[340px] relative list-none"
            >
              {/* Flip container — hover slides the face card up to reveal description */}
              <div
                className="relative h-72 sm:h-80 overflow-hidden"
                onMouseEnter={() => setHoveredCard(index)}
                onMouseLeave={() => setHoveredCard(null)}
                // Keyboard accessibility — allow focus + Enter/Space to trigger hover state
                onFocus={() => setHoveredCard(index)}
                onBlur={() => setHoveredCard(null)}
                tabIndex={0}
                role="article"
                aria-label={service.title}
              >

                {/* ── BACK FACE (description — revealed on hover) ───────────
                    Locked: card background image and overlay are theme assets. */}
                <div className="absolute inset-0 rounded-b-2xl border-x border-b border-[#1B3563]/50 overflow-hidden">
                  {/* Card background image — locked */}
                  <div className="absolute inset-0" aria-hidden="true">
                    <img
                      src="./services-card.jpg"
                      alt=""
                      className="w-full h-full object-cover"
                    />
                    {/* Dark overlay — locked */}
                    <div className="absolute inset-0 bg-[#1B3563]/70" />
                  </div>

                  {/* Description text */}
                  <div className="relative h-full p-6 flex items-center justify-center">
                    <p className="text-white text-sm sm:text-base leading-relaxed text-center">
                      {service.description}
                    </p>
                  </div>
                </div>

                {/* ── FRONT FACE (icon + title — slides away on hover) ───── */}
                <motion.div
                  animate={{ y: hoveredCard === index ? -320 : 0 }}
                  transition={HOVER_SPRING}
                  className="absolute inset-0 bg-gradient-to-b from-[#020207] via-[#020207] to-[#1B3563] backdrop-blur-md border-x border-b border-[#1B3563]/50 rounded-b-2xl shadow-2xl cursor-pointer"
                  aria-hidden={hoveredCard === index} // hidden from AT when description is visible
                >
                  <div className="relative h-full flex flex-col items-center justify-center p-6">

                    {/* Icon — set in services.config.ts cards[n].icon
                        Colors are locked as part of the template theme. */}
                    <div className="mb-6">
                      <div className="relative w-30 h-30 sm:w-30 sm:h-30 rounded-full bg-gradient-to-br from-cyan-500/20 to-purple-500/20 border-2 border-cyan-400/50 flex items-center justify-center">
                        <service.icon
                          className="w-10 h-10 sm:w-12 sm:h-12 text-cyan-400"
                          strokeWidth={1.5}
                          aria-hidden="true"
                        />
                      </div>
                    </div>

                    {/* Card title */}
                    <h3 className="text-white text-lg sm:text-xl md:text-2xl font-bold text-center leading-tight">
                      {service.title}
                    </h3>

                  </div>
                </motion.div>

              </div>
            </motion.li>
          ))}
        </ul>

      </div>
    </section>
  );
};

export default Services;