// =============================================================================
//  Testimonials.tsx — Testimonials carousel component
//  DO NOT edit this file. All customisation is done in testimonials.config.ts
// =============================================================================

import { motion, AnimatePresence } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import testimonialsConfig from '../components/ConfigFiles/testimonialsConfig';

/** How many cards are visible at once in the carousel */
const VISIBLE_CARDS = 3;

/** Milliseconds between automatic slide advances */
const AUTOPLAY_INTERVAL_MS = 4500;

/** Framer Motion cubic-bezier easing for slide animations */
const SLIDE_EASE: [number, number, number, number] = [0.25, 0.46, 0.45, 0.94];

// ─── Framer Motion card variants (locked) ─────────────────────────────────────

const cardVariants = {
  enter: (dir: number) => ({
    x:       dir > 0 ? 120 : -120,
    opacity: 0,
    scale:   0.92,
  }),
  center: {
    x:       0,
    opacity: 1,
    scale:   1,
    transition: { duration: 0.45, ease: SLIDE_EASE },
  },
  exit: (dir: number) => ({
    x:       dir > 0 ? -120 : 120,
    opacity: 0,
    scale:   0.92,
    transition: { duration: 0.35, ease: SLIDE_EASE },
  }),
};

// ─── StarRating sub-component ─────────────────────────────────────────────────

const StarRating = ({ count }: { count: number }) => (
  <div
    className="flex gap-1 mb-5"
    role="img"
    aria-label={`Rated ${count} out of 5 stars`}
  >
    {Array.from({ length: count }).map((_, i) => (
      <svg
        key={i}
        className="w-5 h-5 text-cyan-400"
        fill="currentColor"
        viewBox="0 0 20 20"
        aria-hidden="true"
      >
        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
      </svg>
    ))}
  </div>
);

// ─── TestimonialCard sub-component ───────────────────────────────────────────

const TestimonialCard = ({
  quote,
  name,
  title,
  image,
  rating,
}: {
  quote:  string;
  name:   string;
  title:  string;
  image:  string;
  rating: number;
}) => (
  <figure
    className="relative rounded-2xl p-6 sm:p-7 flex flex-col justify-between min-h-[260px] sm:min-h-[280px]"
    itemScope
    itemType="https://schema.org/Review"
    style={{
      background: 'linear-gradient(145deg, #0d1b2e 0%, #0a1628 100%)',
      border:     '1px solid rgba(255,255,255,0.08)',
      boxShadow:  '0 4px 32px rgba(0,0,0,0.4)',
    }}
  >
    {/* Decorative opening quote mark — hidden from assistive tech */}
    <span
      aria-hidden="true"
      className="text-4xl leading-none mb-3 text-cyan-500 select-none"
      style={{ fontFamily: 'Georgia, serif', lineHeight: 1 }}
    >
      "
    </span>
    <blockquote className="flex-1 mb-5" itemProp="reviewBody">
      <p className="text-gray-300 text-sm sm:text-base leading-relaxed">
        {quote}
      </p>
    </blockquote>

    {/* Star rating — also marked up for Schema.org */}
    <div itemProp="reviewRating" itemScope itemType="https://schema.org/Rating">
      <meta itemProp="ratingValue" content={String(rating)} />
      <meta itemProp="bestRating"  content="5" />
      <StarRating count={rating} />
    </div>

    {/* Visual separator */}
    <div
      className="w-full h-px mb-4"
      aria-hidden="true"
      style={{ background: 'rgba(255,255,255,0.08)' }}
    />
    <figcaption
      className="flex items-center gap-3"
      itemProp="author"
      itemScope
      itemType="https://schema.org/Person"
    >
      <img
        src={image}
        alt={`${name} — ${title}`} // descriptive alt: name + role for context
        width={48}
        height={48}
        className="w-12 h-12 rounded-full object-cover border border-white/20 flex-shrink-0"
        loading="lazy"   // defer loading of off-screen images (improves LCP)
        decoding="async" // decode off main thread (improves TBT)
      />
      <div>
        <p
          className="text-white text-sm font-semibold leading-tight"
          itemProp="name"
        >
          {name}
        </p>
        <p
          className="text-gray-400 text-xs mt-0.5"
          itemProp="jobTitle"
        >
          {title}
        </p>
      </div>
    </figcaption>
  </figure>
);

// ─── Main Testimonials component ──────────────────────────────────────────────

const Testimonials = () => {
  // Pull customisable content from config — nothing else is client-editable
  const { heading, testimonials } = testimonialsConfig;

  const [isVisible,    setIsVisible]    = useState(false);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [direction,    setDirection]    = useState(1); // 1 = forward, -1 = backward

  const sectionRef  = useRef<HTMLDivElement>(null);
  const autoPlayRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // ── Intersection Observer: trigger reveal animation when section enters viewport
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setIsVisible(true); },
      { threshold: 0.2 }
    );
    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  // ── Autoplay: advance carousel every AUTOPLAY_INTERVAL_MS milliseconds
  useEffect(() => {
    autoPlayRef.current = setInterval(() => {
      setDirection(1);
      setCurrentIndex(prev => (prev + 1) % testimonials.length);
    }, AUTOPLAY_INTERVAL_MS);

    return () => { if (autoPlayRef.current) clearInterval(autoPlayRef.current); };
  }, [testimonials.length]);

  /**
   * resetAutoPlay — called after any manual navigation.
   * Prevents the carousel from jumping immediately after the user
   * clicks a button or dot by restarting the interval from zero.
   */
  const resetAutoPlay = () => {
    if (autoPlayRef.current) clearInterval(autoPlayRef.current);
    autoPlayRef.current = setInterval(() => {
      setDirection(1);
      setCurrentIndex(prev => (prev + 1) % testimonials.length);
    }, AUTOPLAY_INTERVAL_MS);
  };

  const goNext = () => {
    setDirection(1);
    setCurrentIndex(prev => (prev + 1) % testimonials.length);
    resetAutoPlay();
  };

  const goPrev = () => {
    setDirection(-1);
    setCurrentIndex(prev => (prev - 1 + testimonials.length) % testimonials.length);
    resetAutoPlay();
  };

  /**
   * visibleCards — derives the VISIBLE_CARDS-length window of testimonials
   * to display, wrapping around the end of the array with modulo arithmetic.
   * This works regardless of how many testimonials are in the config.
   */
  const visibleCards = Array.from({ length: VISIBLE_CARDS }, (_, i) => {
    const idx = (currentIndex + i) % testimonials.length;
    return testimonials[idx];
  });

  return (
    <section
      ref={sectionRef}
      aria-labelledby="testimonials-heading"
      itemScope
      itemType="https://schema.org/ItemList"
      className="relative py-20 sm:py-24 md:py-8 bg-black overflow-hidden"
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* ── Section header ── */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isVisible ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="text-center mb-14 sm:mb-16"
        >
          <p
            aria-hidden="true"
            className="text-cyan-400 text-xs sm:text-sm font-medium tracking-wider uppercase mb-3 sm:mb-4"
          >
            TESTIMONIALS
          </p>

          <h2
            id="testimonials-heading"
            className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-white"
          >
            {heading}
          </h2>
        </motion.div>

        {/* ── Carousel ── */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isVisible ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="relative flex items-center gap-4 sm:gap-6"
        >
          {/* Previous button */}
          <button
            onClick={goPrev}
            aria-label="Previous testimonials"
            className="flex-shrink-0 w-10 h-10 sm:w-20 sm:h-20 rounded-full border border-white/20 bg-white/20 backdrop-blur-sm flex items-center justify-center text-white hover:bg-white/10 hover:border-cyan-400/50 transition-all duration-200 z-10"
          >
            <svg className="w-4 h-4 sm:w-8 sm:h-8" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24" aria-hidden="true">
              <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
            </svg>
          </button>

          {/* Cards track */}
          <div className="flex-1 overflow-hidden">
            <AnimatePresence mode="popLayout" custom={direction}>
              <motion.div
                key={currentIndex}
                custom={direction}
                variants={cardVariants}
                initial="enter"
                animate="center"
                exit="exit"
                className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-5 lg:gap-6"
              >
                {visibleCards.map((testimonial, i) => (
                  <TestimonialCard
                    key={`${testimonial.id}-${i}`}
                    quote={testimonial.quote}
                    name={testimonial.name}
                    title={testimonial.title}
                    image={testimonial.image}
                    rating={testimonial.rating}
                  />
                ))}
              </motion.div>
            </AnimatePresence>
          </div>

          {/* Next button */}
          <button
            onClick={goNext}
            aria-label="Next testimonials"
            className="flex-shrink-0 w-10 h-10 sm:w-20 sm:h-20 rounded-full border border-white/20 bg-white/20 backdrop-blur-sm flex items-center justify-center text-white hover:bg-white/10 hover:border-cyan-400/50 transition-all duration-200 z-10"
          >
            <svg className="w-4 h-4 sm:w-8 sm:h-8" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24" aria-hidden="true">
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
            </svg>
          </button>
        </motion.div>

        {/* ── Dot indicators ── */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={isVisible ? { opacity: 1 } : { opacity: 0 }}
          transition={{ duration: 0.6, delay: 0.6 }}
          className="flex justify-center gap-2 mt-8 sm:mt-10"
          role="tablist"
          aria-label="Testimonial navigation"
        >
          {testimonials.map((t, i) => (
            <button
              key={t.id}
              role="tab"
              aria-selected={i === currentIndex}
              aria-label={`Go to testimonial by ${t.name}`}
              onClick={() => {
                setDirection(i > currentIndex ? 1 : -1);
                setCurrentIndex(i);
                resetAutoPlay();
              }}
              className="transition-all duration-300 rounded-full"
              style={{
                width:      i === currentIndex ? '24px' : '8px',
                height:     '8px',
                background: i === currentIndex ? '#06b6d4' : 'rgba(255,255,255,0.2)',
              }}
            />
          ))}
        </motion.div>

      </div>
    </section>
  );
};

export default Testimonials;