// =============================================================================
//  TrustedLogos.tsx — Social-proof logo strip
//  ⚠️  Do not edit this file. Customise via trustedLogos.config.ts instead.
// =============================================================================

import { useEffect, useRef, useState } from "react";
import trustedLogosConfig from "../components/ConfigFiles/trustedlogosConfig";

const TrustedLogos = () => {
  const sectionRef  = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(false);

  const duplicatedLogos = [
    ...trustedLogosConfig.logos,
    ...trustedLogosConfig.logos,
  ];

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setIsVisible(true); },
      { threshold: 0.1 }
    );
    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  const dur = trustedLogosConfig.scrollDuration ?? 30;

  return (
    <div className="bg-gradient-to-b from-[#020207] via-[#020207] to-[#1B3563]">
      {/*
       * Keyframe injected once — duration comes from config so it stays dynamic.
       * The animation itself runs on the GPU compositor: no JS per frame,
       * no React re-renders, no layout recalculations.
       */}
      <style>{`
        @keyframes tl-marquee {
          from { transform: translateX(0); }
          to   { transform: translateX(-50%); }
        }
        .tl-track {
          animation: tl-marquee ${dur}s linear infinite;
          will-change: transform;
        }
        .tl-track:hover {
          animation-play-state: paused;
        }
      `}</style>

      <section
        ref={sectionRef}
        role="region"
        aria-label={trustedLogosConfig.heading}
        className="relative pt-6 pb-10 mt-4 sm:mt-6 md:mt-8 mx-4 sm:mx-8 md:mx-16 lg:mx-34 px-4 sm:px-8 md:px-12 lg:px-16 overflow-hidden"
      >
        {/* ── Decorative animated borders ── */}
        <div className="absolute left-0 top-0 w-full h-full pointer-events-none" aria-hidden="true">

          <div
            className="absolute left-0 top-0 bottom-0 w-0.5 origin-top transition-transform duration-700 ease-out"
            style={{
              background:     "linear-gradient(to bottom, transparent, #B15DBF, #9CD5F0)",
              transform:      isVisible ? "scaleY(1)" : "scaleY(0)",
              transitionDelay: "600ms",
            }}
          />

          <div
            className="absolute right-0 top-0 bottom-0 w-0.5 origin-top transition-transform duration-700 ease-out"
            style={{
              background:     "linear-gradient(to bottom, transparent, #9CD5F0, #B15DBF)",
              transform:      isVisible ? "scaleY(1)" : "scaleY(0)",
              transitionDelay: "300ms",
            }}
          />

          <div
            className="absolute left-0 right-0 bottom-0 h-0.5 origin-right transition-transform duration-700 ease-out"
            style={{
              background: "linear-gradient(to right, #9CD5F0, #B15DBF)",
              transform:  isVisible ? "scaleX(1)" : "scaleX(0)",
            }}
          />
        </div>

        <div className="max-w-7xl mx-auto">
          <h2 className="text-center text-white/90 text-base sm:text-lg font-medium mb-6 sm:mb-8 md:mb-10">
            {trustedLogosConfig.heading}
          </h2>

          {/*
           * overflow-hidden clips logos outside the viewport.
           * w-max on the ul means it sizes to its full content width,
           * which is exactly 2× the original logo set — the CSS animation
           * shifts it left by 50% and loops, creating a seamless scroll.
           */}
          <div className="relative overflow-hidden" aria-label="Partner and client logos">
            <ul className="tl-track flex gap-8 sm:gap-12 md:gap-16 items-center list-none m-0 p-0 w-max">
              {duplicatedLogos.map((logo, index) => (
                <li key={`${logo.id}-${index}`} className="flex-shrink-0">
                  <img
                    src={logo.imagePath}
                    alt={index < trustedLogosConfig.logos.length ? logo.name : ""}
                    aria-hidden={index >= trustedLogosConfig.logos.length ? true : undefined}
                    className="w-20 sm:w-24 md:w-28 lg:w-32 h-auto opacity-70 hover:opacity-100 transition-opacity duration-300"
                    loading="lazy"
                    decoding="async"
                  />
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>
    </div>
  );
};

export default TrustedLogos;