// =============================================================================
//  TrustedLogos.tsx — Social-proof logo strip
//  ⚠️  Do not edit this file. Customise via trustedLogos.config.ts instead.
// =============================================================================

import { motion, useAnimation } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import trustedLogosConfig from "../components/ConfigFiles/trustedlogosConfig";

const TrustedLogos = () => {
  const controls  = useAnimation();
  const sectionRef = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(false);

  // Duplicate the logo list so the marquee strip appears seamless:
  // when the first set scrolls out of view, the second set has already
  // taken its place — no visible gap or jump.
  const duplicatedLogos = [
    ...trustedLogosConfig.logos,
    ...trustedLogosConfig.logos,
  ];

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) setIsVisible(true);
      },
      { threshold: 0.1 }
    );

    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  // ── Marquee animation ───────────────────────────────────────────────────────
  // Translates the strip left by exactly 50% (the width of one logo set),
  // then loops instantly back to 0 — creating a smooth infinite scroll.
  // Duration is controlled via trustedLogosConfig.scrollDuration.
  useEffect(() => {
    controls.start({
      x: "-50%",
      transition: {
        duration: trustedLogosConfig.scrollDuration,
        ease:     "linear",
        repeat:   Infinity,
      },
    });
  }, [controls]);

  // Helper: restarts the marquee with the configured duration.
  // Extracted to avoid duplicating the transition object in JSX.
  const resumeScroll = () =>
    controls.start({
      x: "-50%",
      transition: {
        duration: trustedLogosConfig.scrollDuration,
        ease:     "linear",
        repeat:   Infinity,
      },
    });

  return (
    <div className="bg-linear-to-b from-[#020207] via-[#020207] to-[#1B3563]">
      <section
        ref={sectionRef}
        role="region"
        aria-label={trustedLogosConfig.heading}
        className="relative pt-6 pb-10 mt-4 sm:mt-6 md:mt-8 mx-4 sm:mx-8 md:mx-16 lg:mx-34 px-4 sm:px-8 md:px-12 lg:px-16 bg-linear-to-b from-[#020207] via-[#020207] to-[#1B3563] overflow-hidden"
      >
        <div
          className="absolute left-0 top-0 w-full h-full pointer-events-none"
          aria-hidden="true"
        >
          {/* Left border — draws top-to-bottom, delayed slightly */}
          <motion.div
            className="absolute left-0 top-0 bottom-0 w-0.5 bg-linear-to-b from-transparent via-[#B15DBF] to-[#9CD5F0]"
            initial={{ scaleY: 0 }}
            animate={isVisible ? { scaleY: 1 } : { scaleY: 0 }}
            transition={{ duration: 0.8, delay: 0.6 }}
            style={{ originY: 0 }}
          />

          {/* Right border — draws top-to-bottom, shorter delay */}
          <motion.div
            className="absolute right-0 top-0 bottom-0 w-0.5 bg-linear-to-b from-transparent via-[#9CD5F0] to-[#B15DBF]"
            initial={{ scaleY: 0 }}
            animate={isVisible ? { scaleY: 1 } : { scaleY: 0 }}
            transition={{ duration: 0.8, delay: 0.3 }}
            style={{ originY: 0 }}
          />

          {/* Bottom border — draws right-to-left, no delay */}
          <motion.div
            className="absolute left-0 right-0 bottom-0 h-0.5 bg-linear-to-r from-[#9CD5F0] to-[#B15DBF]"
            initial={{ scaleX: 0 }}
            animate={isVisible ? { scaleX: 1 } : { scaleX: 0 }}
            transition={{ duration: 0.8 }}
            style={{ originX: 1 }}
          />
        </div>

        <div className="max-w-7xl mx-auto">
          <h2 className="text-center text-white/90 text-base sm:text-lg font-medium mb-6 sm:mb-8 md:mb-10">
            {trustedLogosConfig.heading}
          </h2>

          {/* ── Marquee strip ─────────────────────────────────────────────────
            * overflow-hidden on the wrapper clips the strip at the edges so
            * logos outside the visible area aren't rendered to the user.
            *
            * Pause on hover (onMouseEnter / onMouseLeave) gives keyboard and
            * pointer users a chance to read each logo without it scrolling away.
            */}
          <div
            className="relative overflow-hidden"
            aria-label="Partner and client logos"
          >
            <motion.ul
              className="flex gap-8 sm:gap-12 md:gap-16 items-center list-none m-0 p-0"
              animate={controls}
              initial={{ x: 0 }}
              onMouseEnter={() => controls.stop()}
              onMouseLeave={resumeScroll}
            >
              {duplicatedLogos.map((logo, index) => (
                <li
                  key={`${logo.id}-${index}`}
                  className="flex-shrink-0"
                >
                  <img
                    src={logo.imagePath}
                    alt={index < trustedLogosConfig.logos.length ? logo.name : ""}
                    // Hide duplicate logos from the accessibility tree entirely
                    // so screen readers only announce each brand once.
                    aria-hidden={index >= trustedLogosConfig.logos.length ? true : undefined}
                    className="w-20 sm:w-24 md:w-28 lg:w-32 h-auto opacity-70 hover:opacity-100 transition duration-300"
                    loading="lazy"
                    decoding="async"
                  />
                </li>
              ))}
            </motion.ul>
          </div>

        </div>
      </section>
    </div>
  );
};

export default TrustedLogos;